### ISSUE TITLE
How to use an htmlpanel to initialize a map

### ISSUE THREAD

**Issue by rakesh-roshan** [gwidgets/gwty-leaflet#2]
There are two APIs L.map to initialize map. One takes String id and other takes HTMLElement.
How can I use HTMLPanel widget here. I think if you can provide HTMLElement class extending JavaScriptObject then HTMLPanel::getElement can be used here.

**Comment by zak905** [comment]
If you take a look at the com.gwidgets.api.leaflet.elemental package, there in an HTMLElement class. You can do something like 
```java
HTMLPanel panel = new HTMLPanel("your html");

//...

RootPanel.get().add(panel);
		
HTMLElement mapElement = new HTMLElement();
		
mapElement .setInnerHTML(panel.getElement().getInnerHTML());

final Map map = L.map(mapElement , new MapOptions());
```

**Comment by rakesh-roshan** [comment]
Thanks a lot.  I will try this.

**Comment by zak905** [comment]
Can I close this issue?

**Comment by rakesh-roshan** [comment]
Yeah sure, I have not tried it, but I think it can be closed.

**Comment by zak905** [comment]
Allright. Just a small correction with today's release:

    mapElement.innerHTML = panel.getElement().getInnerHTML();

instead of:

    mapElement .setInnerHTML(panel.getElement().getInnerHTML());

**Comment by rakesh-roshan** [comment]
Thanks a lot for the update
