### ISSUE TITLE
Members of MapOptions are not visible

### ISSUE THREAD

**Issue by rakesh-roshan** [gwidgets/gwty-leaflet#3]
Members in MapOptions have package level visibility. It should be public.

**Comment by zak905** [comment]
Hi @rakesh-roshan, 

Thanks for reporting. It is fixed now. It will take couple of hours to be synchronized in Maven Central.

**Comment by rakesh-roshan** [comment]
Hey thanks a lot for the quick fix. I saw that other option classes also do not have visible fields. I am not currently using them. But it would be better to fix them.

**Comment by zak905** [comment]
They are fixed as well: 669ff6c.

**Comment by rakesh-roshan** [comment]
Awesome :)
